services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

